#!/bin/bash
cd ..
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_debug_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_clang_cpp98
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_bpp
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_boost
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_boost_test
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_boost_test_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_debug_and_release
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_debug_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_oclint
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_qt
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_qt4
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_qt5
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_qt_qtest
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_rcpp
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_sfml
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_sloccount
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_urho3d
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_wt
git clone https://github.com/richelbilderbeek/travis_qmake_clang_cpp11
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_bpp
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_boost
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_boost_test
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_boost_test_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_qt
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_qt_qtest
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_sfml
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_rcpp
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_urho3d
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_wt
git clone https://github.com/richelbilderbeek/travis_qmake_clang_cpp14
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_bpp
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_boost
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_boost_test
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_boost_test_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_gcov
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_qt
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_qt_qtest
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_sfml
git clone https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_urho3d
#git clone https://github.com/richelbilderbeek/qmake_gprof


