site_name: Tutorial how to use Travis CI with C++
repo_url: https://github.com/flywire/travis_cpp_tutorial/
edit_uri: edit/Development/docs/

theme:
    name: material
    
markdown_extensions:
    - toc:
        permalink:
    - admonition
    - def_list
    - nl2br
    - pymdownx.magiclink
    - pymdownx.snippets
    - attr_list
    - markdown_blockdiag:
        format: svg
        
extra_css:
    - css/extra.css
    
plugins:
    - search
    - enumerate-headings:
        toc_depth: 4
  
nav:
    - Tutorial: index.md
